"""Generated by QuantitativeTrading_CLI assembler — do not edit manually."""
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from datamodel import TradingState
from datamodel import Order

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datamodel import TradingState


class MetaStrategy:
    """Universal meta-strategy: MR, Momentum, StatArb, LocArb from a single class.

    signal_m = +1  ->  Mean Reversion  (buy when price is cheap vs EMA)
    signal_m = -1  ->  Momentum         (buy when price breaks out above EMA)
    Multi-asset weights: positive weight = long leg, negative weight = short leg.
    z_entry / z_exit = absolute SeaShell thresholds (not z-scores).
    Edge = signal_m x (Y_current - Y_adj);  BUY when Edge < -Z_ENTRY
    """

    def __init__(self, scope_name, universe, weights, obs_keys, exo_betas,
                 lookback, z_entry, z_exit, inv_skew, gamma, signal_m, limits):
        self.scope_name = scope_name
        self.universe   = universe      # list of product strings
        self.weights    = weights       # OLS hedge ratios; [1.0] for single product
        self.obs_keys   = obs_keys      # ConversionObservation attribute names
        self.exo_betas  = exo_betas     # corresponding betas
        self.lookback   = lookback      # EMA window N; alpha = 2/(N+1)
        self.z_entry    = z_entry       # entry threshold in absolute SeaShells
        self.z_exit     = z_exit        # exit threshold in absolute SeaShells (< z_entry)
        self.inv_skew   = inv_skew      # inventory adjustment in price units
        self.gamma      = gamma         # informed-flow absolute tick multiplier (0 = disabled)
        self.signal_m   = signal_m      # +1 = Mean Reversion,  -1 = Momentum
        self.limits     = limits        # dict: product -> position limit

    def run(self, state: "TradingState", ctx: dict, positions: dict | None = None) -> list:
        from datamodel import Order

        _k = "_MS_" + self.scope_name
        _s = ctx.setdefault(_k, {})
        _ema  = _s.get("e")
        _t    = _s.get("t", 0)
        _dh   = _s.get("dh")
        _dl   = _s.get("dl")

        # -- Best mids + micro-prices ------------------------------------------
        _mids  = {}
        _micro = {}
        for _p in self.universe:
            _od = state.order_depths.get(_p)
            if not _od or not _od.buy_orders or not _od.sell_orders:
                return []
            _bb = max(_od.buy_orders)
            _ba = min(_od.sell_orders)
            _mids[_p] = (_bb + _ba) / 2.0
            _bv = float(_od.buy_orders[_bb])
            _av = abs(float(_od.sell_orders[_ba]))
            _tv = _bv + _av
            if _tv > 0:
                _imb = _bv / _tv
                _micro[_p] = _ba * _imb + _bb * (1.0 - _imb)
            else:
                _micro[_p] = _mids[_p]

        # -- Synthetic target  Y = sum(W_i * micro_i) -------------------------
        _Y = sum(_w * _micro[_p] for _w, _p in zip(self.weights, self.universe))

        # -- Exogenous betas ---------------------------------------------------
        if self.obs_keys:
            _conv = getattr(getattr(state, "observations", None),
                            "conversionObservations", {})
            _cobs = _conv.get(self.universe[0])
            for _ok, _ob in zip(self.obs_keys, self.exo_betas):
                _oval = getattr(_cobs, _ok, None) if _cobs else None
                if _oval is not None:
                    _Y += _ob * float(_oval)

        # -- EMA baseline ------------------------------------------------------
        _alpha = 2.0 / (max(self.lookback, 1) + 1)
        _ema   = _Y if _ema is None else (1.0 - _alpha) * _ema + _alpha * _Y
        _t    += 1
        _s["e"] = _ema
        _s["t"] = _t

        # -- Daily extrema tracker --------------------------------------------
        _p0m = _mids[self.universe[0]]
        _s["dh"] = _p0m if _dh is None else max(_dh, _p0m)
        _s["dl"] = _p0m if _dl is None else min(_dl, _p0m)
        _dh = _s["dh"]; _dl = _s["dl"]

        if _t < max(2, int(self.lookback) // 5 or 2):
            return []

        _pos_map = positions if positions is not None else state.position

        # -- Inventory-adjusted fair value ------------------------------------
        _pri       = self.universe[0]
        _pos       = _pos_map.get(_pri, 0)
        _pos_ratio = abs(_pos) / max(self.limits.get(_pri, 1), 1)
        _pos_sign  = 1 if _pos > 0 else (-1 if _pos < 0 else 0)
        _adj = _ema - _pos_sign * (_pos_ratio ** 2) * self.inv_skew

        # -- Daily extrema signal (gated: burn-in 100 ticks) ------------------
        if self.gamma != 0.0 and _t >= 100:
            _p0_mid_now = _mids[self.universe[0]]
            if _p0_mid_now <= _dl + 1.0:
                _ext = 1.0
            elif _p0_mid_now >= _dh - 1.0:
                _ext = -1.0
            else:
                _ext = 0.0
            _adj = _adj + _ext * self.gamma

        # -- Edge = signal_m * (Y - Y_adj) ------------------------------------
        _edge = self.signal_m * (_Y - _adj)

        # -- Price helpers -----------------------------------------------------
        def _agg_price(_p, _buy: bool) -> int:
            _od = state.order_depths.get(_p)
            if _od:
                if _buy and _od.sell_orders:
                    return min(_od.sell_orders.keys())
                if not _buy and _od.buy_orders:
                    return max(_od.buy_orders.keys())
            return int(_mids.get(_p, 0))

        _orders = []
        _p0_mid = _mids[self.universe[0]]
        _is_cm  = (len(self.universe) == 1 and self.signal_m == 1)

        if len(self.universe) == 1:
            # -- Single-asset: edge-based execution ----------------------------
            _buy_cond  = _is_cm or _edge < -self.z_entry
            _sell_cond = _is_cm or _edge >  self.z_entry

            _p0_lim = self.limits.get(self.universe[0], 0)
            _k_buy  = _p0_lim
            _k_sell = _p0_lim
            for _p, _w in zip(self.universe, self.weights):
                _wr   = int(round(_w))
                if _wr == 0:
                    continue
                _lim  = self.limits.get(_p, 0)
                _curr = _pos_map.get(_p, 0)
                if _wr > 0:
                    _k_buy  = min(_k_buy,  (_lim - _curr) // _wr)
                    _k_sell = min(_k_sell, (_lim + _curr) // _wr)
                else:
                    _k_buy  = min(_k_buy,  (_lim + _curr) // abs(_wr))
                    _k_sell = min(_k_sell, (_lim - _curr) // abs(_wr))

            if _buy_cond and _k_buy > 0:
                _spread_tgt = _adj - self.z_entry
                for _i, (_p, _w) in enumerate(zip(self.universe, self.weights)):
                    _wr = int(round(_w))
                    if _wr == 0:
                        continue
                    _q = _wr * _k_buy
                    if _i == 0 and self.signal_m == 1:
                        _theo = int(round(_p0_mid + (_spread_tgt - _Y)))
                        _ba   = _agg_price(_p, True)
                        _price = _ba if _ba <= _theo else _theo
                    else:
                        _price = _agg_price(_p, _q > 0)
                    _orders.append(Order(_p, _price, _q))

            if _sell_cond and _k_sell > 0:
                _spread_tgt = _adj + self.z_entry
                for _i, (_p, _w) in enumerate(zip(self.universe, self.weights)):
                    _wr = int(round(_w))
                    if _wr == 0:
                        continue
                    _q = -_wr * _k_sell
                    if _i == 0 and self.signal_m == 1:
                        _theo = int(round(_p0_mid + (_spread_tgt - _Y)))
                        _bb   = _agg_price(_p, False)
                        _price = _bb if _bb >= _theo else _theo
                    else:
                        _price = _agg_price(_p, _q < 0)
                    _orders.append(Order(_p, _price, _q))

            if not _is_cm and _pos != 0 and abs(_edge) < self.z_exit:
                _spread_tgt = _adj
                for _i, (_p, _w) in enumerate(zip(self.universe, self.weights)):
                    _q_open  = int(round(_w)) * _pos
                    if _q_open == 0:
                        continue
                    _q_close = -_q_open
                    if _i == 0 and self.signal_m == 1:
                        _price = int(_p0_mid + (_spread_tgt - _Y))
                    else:
                        _price = _agg_price(_p, _q_close > 0)
                    _orders.append(Order(_p, _price, _q_close))

        else:
            # -- Multi-asset: Lead-Lag Delta Hedging ---------------------------
            _p0 = self.universe[0]

            _k_buy  = self.limits.get(_p0, 0)
            _k_sell = self.limits.get(_p0, 0)
            for _p, _w in zip(self.universe, self.weights):
                _wr   = int(round(_w))
                if _wr == 0:
                    continue
                _lim  = self.limits.get(_p, 0)
                _curr = _pos_map.get(_p, 0)
                if _wr > 0:
                    _k_buy  = min(_k_buy,  (_lim - _curr) // _wr)
                    _k_sell = min(_k_sell, (_lim + _curr) // _wr)
                else:
                    _k_buy  = min(_k_buy,  (_lim + _curr) // abs(_wr))
                    _k_sell = min(_k_sell, (_lim - _curr) // abs(_wr))
            _k_buy  = max(0, _k_buy)
            _k_sell = max(0, _k_sell)

            _p0_pos = _pos_map.get(_p0, 0)

            if _edge < -self.z_entry and _k_buy > 0:
                _spread_tgt = _adj - self.z_entry
                _price = int(round(_p0_mid + (_spread_tgt - _Y)))
                _orders.append(Order(_p0, _price, _k_buy))

            if _edge > self.z_entry and _k_sell > 0:
                _spread_tgt = _adj + self.z_entry
                _price = int(round(_p0_mid + (_spread_tgt - _Y)))
                _orders.append(Order(_p0, _price, -_k_sell))

            if _p0_pos != 0 and abs(_edge) < self.z_exit:
                _spread_tgt = _adj
                _price = int(round(_p0_mid + (_spread_tgt - _Y)))
                _orders.append(Order(_p0, _price, -_p0_pos))

            for _p, _w in zip(self.universe[1:], self.weights[1:]):
                _wr = int(round(_w))
                if _wr == 0:
                    continue
                _target = _p0_pos * _wr
                _curr   = _pos_map.get(_p, 0)
                _delta  = _target - _curr
                if _delta == 0:
                    continue
                _lim_c = self.limits.get(_p, 0)
                _q = max(-(_lim_c + _curr), min(_lim_c - _curr, _delta))
                if _q == 0:
                    continue
                _price = _agg_price(_p, _q > 0)
                _orders.append(Order(_p, _price, _q))

        return _orders



class Trader:
    """Entry point called by the IMC Prosperity platform."""

    def __init__(self):
        self.strategies = [
            MetaStrategy(
                scope_name='EMERALDS',
                universe=['EMERALDS'],
                weights=[1.0],
                obs_keys=[],
                exo_betas=[],
                lookback=10,
                z_entry=7.87,
                z_exit=3.935,
                inv_skew=4.7201,
                gamma=0.0,
                signal_m=1,
                limits={'EMERALDS': 80},
            ),
            MetaStrategy(
                scope_name='TOMATOES',
                universe=['TOMATOES'],
                weights=[1.0],
                obs_keys=[],
                exo_betas=[],
                lookback=5,
                z_entry=6.53,
                z_exit=3.265,
                inv_skew=3.9196,
                gamma=0.0,
                signal_m=1,
                limits={'TOMATOES': 80},
            ),
        ]

    def run(self, state: "TradingState") -> tuple[dict, int, str]:
        import json as _json
        try:
            ctx: dict = _json.loads(state.traderData) if state.traderData else {}
        except Exception:
            ctx = {}
        orders: dict[str, list] = {}
        # Shared position tracker: updated after each strategy fires so later
        # strategies see capacity already committed by earlier ones this tick.
        _positions: dict = dict(state.position)

        # Edge-priority sort for ETF strategies: the strategy with the largest
        # abs(edge) this tick gets first access to shared component limits
        # (e.g. CROISSANTS, JAMS).  Uses the previous tick's EMA from ctx so
        # there are no side-effects during scoring.  Non-ETF strategies keep
        # their original order and always run after ETF ones.
        def _etf_edge(_s):
            if not hasattr(_s, 'e_enter_start'):
                return 0.0
            _k  = "_ETF_" + _s.scope_name
            _em = ctx.get(_k, {}).get("e")
            if _em is None:
                return 0.0
            _Y = 0.0
            for _p, _w in zip(_s.universe, _s.weights):
                _od = state.order_depths.get(_p)
                if not _od or not _od.buy_orders or not _od.sell_orders:
                    return 0.0
                _Y += _w * (max(_od.buy_orders) + min(_od.sell_orders)) / 2.0
            _raw = abs(_s.signal_m * (_Y - _em))
            _max_w = max(
                (abs(int(round(_w))) for _w in _s.weights[1:] if int(round(_w)) != 0),
                default=1,
            )
            return _raw / max(_max_w, 1)

        _etf_strats   = sorted(
            [_s for _s in self.strategies if hasattr(_s, 'e_enter_start')],
            key=_etf_edge, reverse=True,
        )
        _other_strats = [_s for _s in self.strategies if not hasattr(_s, 'e_enter_start')]

        for _strat in _etf_strats + _other_strats:
            for _o in _strat.run(state, ctx, _positions):
                orders.setdefault(_o.symbol, []).append(_o)
                _positions[_o.symbol] = _positions.get(_o.symbol, 0) + _o.quantity
        return orders, 0, _json.dumps(ctx)
